### ISSUE TITLE
希望能够不唤醒微信发送消息

### ISSUE THREAD

**Issue by lun9090** [cluic/wxauto#1]
太给力了，希望一直更新
这代码写的真给力，厉害厉害
我测试了下 真是很给力

**Comment by cluic** [comment]
感谢支持，非常感谢！
目前是基于微信客户端的UI页面进行操作的，所以还没办法做到激活微信窗口就发送消息，后续会研究看看有没有方法可以实现

**Comment by cluic** [comment]
> 太给力了，希望一直更新
> 这代码写的真给力，厉害厉害
> 我测试了下 真是很给力

感谢支持，非常感谢！
目前是基于微信客户端的UI页面进行操作的，所以还没办法做到激活微信窗口就发送消息，后续会研究看看有没有方法可以实现

**Comment by lun9090** [comment]
我的用户名就是我的微信，我调整了部分示例代码，我不是专业的开发，只是会一点python，可以加我，空了我发给你

**Comment by PuffLiu** [comment]
关注一波。
除了这推发消息之外，微信公众号文章的获取可能也可以用到客户端实现。 几年前的wechatsogou通过搜狗搜公众号文章的方法被屏蔽了。

**Comment by cluic** [comment]
> 关注一波。
> 除了这推发消息之外，微信公众号文章的获取可能也可以用到客户端实现。 几年前的wechatsogou通过搜狗搜公众号文章的方法被屏蔽了。

感谢建议，后续会做研究看看~
