### ISSUE TITLE
能否有个实时读取微信群聊的功能

### ISSUE THREAD

**Issue by pp852938677** [cluic/wxauto#10]
能否有个实时读取微信群聊  并发送文件给具体群聊的人

感谢

**Comment by cluic** [comment]
1. 实时读取的话需要一直将群聊处于激活状态
2. 在群里面发送文件可以使用 SendFiles 方法发送文件，给群聊具体人私聊的话需要好友，这个可以自行结合目前的方法实现

**Comment by pp852938677** [comment]
我可以加你一个联系方式吗
