### ISSUE TITLE
GetSessionList  获取聊天列表name的问题

### ISSUE THREAD

**Issue by bosunram** [cluic/wxauto#151]
Version: 3.9.8.15
Update: 2023-11-22
昨天最后的一个版本

当对话昵称（备注）末尾有数字时，比如【太阳30】，并且有新消息时，1或者多条，GetSessionList 获取的字典name中是【太阳】

name 末尾的数字与X条新消息干扰  直接去掉了   导致取值失败，后面ChatWith 时直接报错

**Comment by cluic** [comment]
先给这种群改个备注吧，我考虑一下怎么判断这种情况

**Comment by cluic** [comment]
已修复
