### ISSUE TITLE
ImportError: cannot import name 'WeChat' from 'wxauto' (unknown location)

### ISSUE THREAD

**Issue by qingshui1221** [cluic/wxauto#154]
作者的demo能正常运行。自己import WeChat就报错

**Comment by cluic** [comment]
路径要对才行，如果demo能运行，**那就把demo.py同目录下的wxauto**这个文件夹放到python根目录下/Lib/site-packages文件夹里面去，就可以全局调用了
```python
from wxauto import WeChat

**Comment by qingshui1221** [comment]
是放到了/Lib/site-packages这里。还是不行。然后我把自己的代码放进作者的demo里（复制到site-packages的demo），能运行。但是GetAllMessage返回的不是一个列表嘛，报错TypeError: 'method' object is not iterable

**Comment by yexp11235** [comment]
您好, 我也遇到了一样的问题, 请问您解决了吗

**Comment by DiQlearner** [comment]
我也是这样的问题，import WeChat报错，按照作者的方法还是未能解决
