### ISSUE TITLE
关于内存溢出的问题

### ISSUE THREAD

**Issue by bosunram** [cluic/wxauto#169]
用wxauto 写了个机器人，使用一年多了，一直有个问题困扰

因为目前的监控方式，设置的是60秒循环，1天就是1440次，每7天电脑的8G物理内存会从20%增长到80%，就需要重启一次，否则就会内存溢出。

我自己程序部分也检查了一些内存监控的方法，收效甚小，请大神看看wxauto包有没有改进的空间。

**Comment by cluic** [comment]
可以看下你的代码吗
