### ISSUE TITLE
2024-02-18 21:57:36.934 wxauto.py[48] SplitMessage -> Find Control Timeout(0s): {ControlType: ButtonControl}

### ISSUE THREAD

**Issue by HowardJoness** [cluic/wxauto#177]
报2024-02-18 21:57:36.934 wxauto.py[48] SplitMessage -> Find Control Timeout(0s): {ControlType: ButtonControl}后停止收发消息

**Comment by cluic** [comment]
github下载最新代码，不要pip安装
