### ISSUE TITLE
聊天被挂起时无法发送消息？

### ISSUE THREAD

**Issue by gao-gao-zai** [cluic/wxauto#180]
当聊天被挂起时，无法使用SendMsg发送消息
![PixPin_2024-02-22_20-25-27](https://github.com/cluic/wxauto/assets/152040549/805df77a-c31d-476f-afb7-2e363f83fc5a)

**Comment by benyazi001** [comment]
被动挂起的话加个检测，如果挂起了就x掉就行了

**Comment by gao-gao-zai** [comment]
AddListenChat和GetListenMessage不是会自动将聊天挂起吗？

**Comment by cluic** [comment]
已经修复了，下载最新代码试试
