### ISSUE TITLE
锁屏后还能使用吗？

### ISSUE THREAD

**Issue by mycfctech** [cluic/wxauto#182]
RT，希望用在远程服务器上，在没有连接的情况下还能使用吗？

**Comment by jinde98** [comment]
锁屏后无法使用，这是模拟键盘输入的。

**Comment by cluic** [comment]
可参考[这里](https://github.com/cluic/wxauto/blob/WeChat3.9.8/%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3.md#%E4%BA%94%E4%BA%91%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%83%A8%E7%BD%B2)解决远程服务器锁屏问题
