### ISSUE TITLE
可以获取某个群聊的所有用户名么？

### ISSUE THREAD

**Issue by ice1025** [cluic/wxauto#183]

**Comment by cluic** [comment]
加上了新方法：GetGroupMembers

**Comment by jingle1267** [comment]
调用GetGroupMembers报错：raise LookupError('Find Control Timeout({}s): {}'.format(maxSearchSeconds, self.GetSearchPropertiesStr()))

**Comment by ice1025** [comment]
> 调用GetGroupMembers报错：raise LookupError('Find Control Timeout({}s): {}'.format(maxSearchSeconds, self.GetSearchPropertiesStr()))

是不是你客户端版本问题，我测试正常

**Comment by jingle1267** [comment]
我更新到3.9.8.15版本试了也是一样的报错
