### ISSUE TITLE
发送文件超时

### ISSUE THREAD

**Issue by aaeddy** [cluic/wxauto#185]
```python
from wxauto import WeChat

wx = WeChat()
who = 'ABC'
audioPath = r'下载音频\audio_20240302112702.mp3'  # 这里如果是现在这样的相对路径就会报错


wx.SendFiles(filepath=audioPath, who=who)
```
给ABC发文件时，audioPath必须是绝对路径，写相对路径会报
`
File "C:\Users\abc18\Desktop\WechatBot\wxauto\wxauto.py", line 295, in SendFiles
`
`
raise TimeoutError(f'发送文件超时 --> {filelist}')
`
`
TimeoutError: 发送文件超时 --> ['下载音频\\audio_20240302112702.mp3']
`

**Comment by cluic** [comment]
已修复
