### ISSUE TITLE
这个wx库对python3.10是不兼容嘛，我程序定时跑发几个人就抛异常

### ISSUE THREAD

**Issue by zxnliu** [cluic/wxauto#20]

**Comment by cluic** [comment]
具体是什么异常呢

**Comment by zxnliu** [comment]
发了几个人就抛异常，有找不到要发信息的那个人，超时啥的，是不能用死循环吗还是啥

**Comment by zxnliu** [comment]
微信和py版本和开发者给出的版本不同有影响吗？

**Comment by cluic** [comment]
如果能成功发送的话，那py的版本是没有问题的；
但是如果作为一个自动化服务长期运行可能还存在一些需要优化的地方，目前来说不够稳定，电脑卡顿、网络波动等都有可能影响正常运行

**Comment by zxnliu** [comment]
好的谢谢，我研究 一下有优化长期运行方法
