### ISSUE TITLE
GetAllMessage TypeError

### ISSUE THREAD

**Issue by Davidyang1989** [cluic/wxauto#22]
GetAllMessage() returned a TypeError that "list_object_is_not_callable"
But there is not list type params I entered, who so?
Is it my input fault or bug
![GetAllMessage_TypeError_list_object_is_not_callable](https://user-images.githubusercontent.com/23066630/163670278-e9fc15a3-7047-4b37-8090-7702344f4f78.png)
?

**Comment by cluic** [comment]
wx.GetAllMessage
not： wx.GetAllMessage( )
