### ISSUE TITLE
多窗口挂起NameError: name 'editbox' is not defined

### ISSUE THREAD

**Issue by ndmiao** [cluic/wxauto#224]
![image](https://github.com/cluic/wxauto/assets/44725449/ffef9b8d-b46b-4b6b-96ce-f5bcc4df0bb1)
![image](https://github.com/cluic/wxauto/assets/44725449/437f4efa-7875-4b15-9ebf-1d654aa86339)
微信：3.9.8.15
wxauto: 3.9.8.15.4

**Comment by ndmiao** [comment]
![image](https://github.com/cluic/wxauto/assets/44725449/0fbaa098-0bf7-42fd-8812-5d0ba98969e0)
漏了self

**Comment by cluic** [comment]
收到，谢谢提醒
