### ISSUE TITLE
运行时报错了

### ISSUE THREAD

**Issue by Pandar1Young** [cluic/wxauto#250]
-----------------代码-----------------
```
# 导入
from wxauto import WeChat

# 获取微信窗口对象
wx = WeChat()
# 输出 > 初始化成功，获取到已登录窗口：xxxx
```
------------------------------------------

-----------------报错-----------------
```
Traceback (most recent call last):
  File "C:\Users\xxx\Pycharm\pythonProject\wxauto.py", line 2, in <module>
    from wxauto import WeChat
  File "C:\Users\xxx\Pycharm\pythonProject\wxauto.py", line 2, in <module>
    from wxauto import WeChat
ImportError: cannot import name 'WeChat' from partially initialized module 'wxauto' (most likely due to a circular import) (C:\Users\xxxx\Pycharm\pythonProject\wxauto.py)
```

------------------------------------------

-----------------环境-----------------
Python Version：Python 3.12.3
OS：Windows 11
IDE：Pycharm
微信版本：3.9.11.19
------------------------------------------

**Comment by LiLiLiam** [comment]
我也是这个问题 你解决了吗

**Comment by CaixyPromise** [comment]
修改文件名好了，你的py运行文件叫做wxauto。py把from wxauto import WeChat的wxauto理解成你当前文件了。不要重名了！

**Comment by Pandar1Young** [comment]
> 修改文件名好了，你的py运行文件叫做wxauto。py把from wxauto import WeChat的wxauto理解成你当前文件了。不要重名了！

是这个问题！ python小白见笑了

**Comment by Pandar1Young** [comment]
> 我也是这个问题 你解决了吗

我这可以了 你改下py的文件名
