### ISSUE TITLE
昵称或者微信ID发送超时情况解决办法

### ISSUE THREAD

**Issue by lucoo** [cluic/wxauto#290]
wx = WeChat()
    wx.ChatWith('昵称')
    wx.SendMsg('多方两天假')    获取微信窗口和发送消息分开写，就能避免超时问题

**Comment by lucoo** [comment]
感谢微信4群  李春宝  兄弟

**Comment by lucoo** [comment]
以上是解决方案

**Comment by lichunbao8888** [comment]
> 感谢微信4群 李春宝 兄弟

我来了
