### ISSUE TITLE
发送消息时，遇到换行无效情况

### ISSUE THREAD

**Issue by UioCat** [cluic/wxauto#42]
日志打印出来发送消息前是存在换行的，调用的方法是：wx.SendMsg(message)
<img width="615" alt="image" src="https://user-images.githubusercontent.com/54000048/184674301-de8411ac-dfde-42d4-b3c4-bff5cb22e1f7.png">
收到的消息不存在换行
<img width="305" alt="image" src="https://user-images.githubusercontent.com/54000048/184674346-0b4c2ab9-e52f-4853-a9ba-b27e36379fc7.png">

**Comment by UioCat** [comment]
\r\n和\n都是这样

**Comment by cluic** [comment]
换行的问题可以查看 #23

**Comment by UioCat** [comment]
解决了
