### ISSUE TITLE
搜索接收人的时候  微信匹配错了人  怎么办？ 见图片

### ISSUE THREAD

**Issue by mjljy** [cluic/wxauto#46]
是有1个 1#的微信群   但是在微信搜索匹配的时候  第一个匹配是 001#   但是下面是有1#这个微信群的  所以微信匹配错了 怎么办
![image](https://user-images.githubusercontent.com/60380209/186370622-56092ba9-9c3c-4d5d-a5f6-8350923041b3.png)

**Comment by cluic** [comment]
这个没有办法，最好是单独做好备注，然后完全匹配关键字

**Comment by mjljy** [comment]
没有办法
