### ISSUE TITLE
相关问题提问

### ISSUE THREAD

**Issue by masterkilla1** [cluic/wxauto#5]
您好  我想咨询一下  如果现在微信更新版本 这个代码还能用吗？
还有  每次发送消息都会弹出微信  可以不弹出吗？

**Comment by cluic** [comment]
不能不弹出来，因为是模拟人的操作来发送消息的

**Comment by masterkilla1** [comment]
那如果我服务器上刚好有人操作不就废了?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月25日(星期六) 晚上10:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cluic/wxauto] 相关问题提问 (#5)





 
不能不弹出来，因为是模拟人的操作来发送消息的
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cluic** [comment]
从原理上没办法做到后台运行，必须要激活窗口，就像人一样发消息
