### ISSUE TITLE
虚拟机无法断开

### ISSUE THREAD

**Issue by ouwx** [cluic/wxauto#89]
我在网上买的windows 7虚拟机，当我登录在线时各功能都正常，但是当我远程桌面断开连接后就无法自动化了，不知道何解？

**Comment by cluic** [comment]
不要用mstsc远程服务器，断开会锁屏，导致无法运行；在服务器下载安装VNC Server，本地电脑安装VNC Viewer，用VNC进行远程控制不会锁屏




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月25日(星期六) 下午5:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [cluic/wxauto] 虚拟机无法断开 (Issue #89)





 
我在网上买的windows 7虚拟机，当我登录在线时各功能都正常，但是当我远程桌面断开连接后就无法自动化了，不知道何解？

**Comment by ouwx** [comment]
感谢，已经按这个方法解决
