### ISSUE TITLE
有没高效率监听方案？

### ISSUE THREAD

**Issue by bhj8** [cluic/wxauto#91]
现在监听新消息，我都是用笨办法。拿整个聊天列表名单，一个一个查聊天记录过去。。好傻瓜啊。。。
有没有靠速度更快的方案？拿聊天列表跑一次要5秒左右，很慢啊。

**Comment by cluic** [comment]
wxauto的话目前只能用笨办法
后台协议版本，比较快，可以加qq271374208了解

**Comment by wxq3d** [comment]
我也正想问，看到了 。谢谢兄弟！@cluic

**Comment by 20040714Mike** [comment]
开启 多线程 或者 异步 处理的库。或者用点算法，例如使用 反向线段树 来查异样。

**Comment by bhj8** [comment]
我的号已经被ban了，个人建议也不要在用个人微信号，和这个库了。作者都跑路了。超级难用。
直接转用公众号了，稳定合法接口好处理。

Mike Long ***@***.***> 于2023年3月11日周六 11:05写道：
